### PR TITLE
Use GitHub API to generate profiles.json

### PR DESCRIPTION
**Pull request by eliminmax**
**Checklist**

- [x] Closing issues: #32, #28
- [x] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some documentation

**Description**

Instead of using the bundled `profile.json`, dynamically generate one within `r2env_path` using info pulled from GitHub's API.

If that `profile.json` file does not exist, it creates it.

Adds an `update` subcommand command to re-create the `profile.json` file

### CODE REVIEW

**Comment by eliminmax** [comment]
Couple of issues came up right after I opened this pull request:

* I noticed that the added `update` subcommand was missing in the README file's Help section
* I realized that I'd forgotten to remove the bundled `profiles.json` file even though it's 
* I realized that the order of releases listed by `r2env list` switched from ascending order to descending order.

After making those changes, I ran `run_tests.sh`, and all tests passed.

**Comment by as0ler** [comment]
LGTM! But could you please fix the pylint, flake9, and unit tests to make them green? 

Moreover, we should consider the git package for radare2 too:

```
{
         "id": "git",
         "packages": {}
}
```

**Comment by eliminmax** [comment]
The list includes the git package already.

I know "it works on my machine" is not a helpful answer, but the unit tests all succeed when I run `run_tests.sh` locally on my machine. Looking at the error message for the linux-unit-tests check, I see the following line:

```
py38-tests: failed with /home/runner/work/r2env/r2env/run_tests.sh (resolves to /home/runner/work/r2env/r2env/run_tests.sh) is not allowed, use allowlist_externals to allow it
```

That seems to indicate that the failure there is an authorization issue. I just enabled the workflow for my fork, so hopefully the next time I push a commit to the branch, it works.

The flake8 test simply says that the PackageManager.update_radare2_profiles function I implemented is "too complex", which is a rather vague issue, and I'm not sure how I'd go about solving it, but the pylint issues are more specific, and I suspect that addressing those would also address the "too complex" issue. I'll try to refactor it to satisfy the issues raised, then comment again once I've done so.

**Comment by eliminmax** [comment]
I've refactored the `PackageManager.update_radare2_profiles` function, and I ran the `run_tests.sh` directly - all tests passed.

I do not have Python 3.8 installed, but both `tox -e py39-codecheck-pylint` and `tox -e py39-codecheck-flake8` run without finding any issues.

I compared the `profiles.json` file generated by the latest commit to the one generated by the un-refactored version, and they were identical.

**Pull request merged**
